version: '3'

services:
  queue:
    build: ActiveMQ
    ports:
      - "61613:61613"
      - "61614:61614"
      - "8161:8161"
  # queue2:
  #   build: ActiveMQ
  # queue3:
  #   build: ActiveMQ
  postgres:
    build: Postgres
    ports: 
      - "5432:5432"
    environment:
      - DEBUG=false
      - DB_USER=postgres
      - DB_PASS=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  warehouse-admin:
    # ports:
    #   - "5000:5000"
    depends_on:
      - postgres
      - queue
      - message-bus
    environment:
      PYTHONUNBUFFERED: 1
    build: WarehouseAdminInterface
  warehouse-message-handler:
    depends_on:
      - postgres
      - queue
      - message-bus
    build: WarehouseMessageHandler
    volumes:
      - ./Connection:/app/Connection
  message-bus:
    depends_on:
      - postgres
      - queue
    environment:
      PYTHONUNBUFFERED: 1
    build: MessageBus
  store:
    depends_on:
      - message-bus
      - warehouse-message-handler
      - warehouse-admin
    build: Store
    ports:
      - "80:80"
  translator:
    depends_on:
      - message-bus
    build: Translator
  
volumes:
  postgres-data: