version: '3'

services:
  queue:
    build: ActiveMQ
    ports:
      - "61613:61613"
      - "8161:8161"
  postgres:
    build: Postgres
    ports: 
      - "5432:5432"
    environment:
      - DEBUG=false
      - DB_USER=postgres
      - DB_PASS=postgres

    volumes:
      - postgres-data:/var/lib/postgresql/data
  warehouse-admin:
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - queue
    build: WarehouseAdminInterface
  warehouse-message-handler:
    depends_on:
      - postgres
      - queue
    build: WarehouseMessageHandler
  
volumes:
  postgres-data: