version: '3'

services:
  controlbus:
    build:
      context: .
      dockerfile: ./controlbus/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - control-queue
  main-queue:
    build: ActiveMQ
    ports:
      - "62614:61614"
  control-queue:
    build: ActiveMQ
    ports:
      - "62615:61614"
      - "8161:8161"
  backup-queue:
    build: ActiveMQ
    ports:
      - "62616:61614"
  postgres:
    build: Postgres
    ports: 
      - "5432:5432"
    environment:
      - DEBUG=false
      - DB_USER=postgres
      - DB_PASS=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  warehouse-admin:
    depends_on:
      - postgres
      - main-queue
      - message-bus
    environment:
      PYTHONUNBUFFERED: 1
    build: WarehouseAdminInterface
    volumes:
      - ./Connection:/app/Connection
  warehouse-message-handler:
    depends_on:
      - postgres
      - main-queue
      - message-bus
    build: WarehouseMessageHandler
    volumes:
      - ./Connection:/app/Connection
  message-bus:
    depends_on:
      - postgres
      - main-queue
    environment:
      PYTHONUNBUFFERED: 1
    build: MessageBus
  store:
    depends_on:
      - message-bus
      - warehouse-message-handler
      - warehouse-admin
    build: Store
    ports:
      - "80:80"
  translator:
    depends_on:
      - message-bus
    build: Translator
    volumes:
      - ./Connection:/app/Connection

volumes:
  postgres-data: