@startuml

skinparam componentStyle uml2

ESB -- WarehouseService
ESB -- AdminService
ESB -- NlStore
ESB -- GbStore
ESB -- PricingTranslater
ESB -- PricingTranslater2

component "ESB" {
[ControlBus] - [MessageBus]
[MessageQueue] - [MessageBus]
[MessageQueue] - [ControlBus]
}

component "WarehouseService" {
[WarehouseBackend] - [WarehouseDatabase]
}

component "AdminService" {
[AdminBackend] - [AdminUi]
}

component "NlStore" {
[StoreNlUi]
}

component "GbStore" {
[StoreGbUi]
}

component "PricingTranslater" {

}

component "PricingTranslater2" {

}

@enduml